// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGni_o5acwmO-cAijEHztClZGzbk-AWI',
    appId: '1:66332621949:web:1173f24f7ced63ff0b0514',
    messagingSenderId: '66332621949',
    projectId: 'mynotes-camel-flutter',
    authDomain: 'mynotes-camel-flutter.firebaseapp.com',
    storageBucket: 'mynotes-camel-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6QaNNUFDe4sKRNNOMt2Q7tmPFEdcsyU0',
    appId: '1:66332621949:android:bf171543577ea2220b0514',
    messagingSenderId: '66332621949',
    projectId: 'mynotes-camel-flutter',
    storageBucket: 'mynotes-camel-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWpFQZXklkcz2BQ-c9iTZZHMztAyS0NQ',
    appId: '1:66332621949:ios:4a14fe4b220bd4110b0514',
    messagingSenderId: '66332621949',
    projectId: 'mynotes-camel-flutter',
    storageBucket: 'mynotes-camel-flutter.appspot.com',
    iosBundleId: 'com.camel.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWpFQZXklkcz2BQ-c9iTZZHMztAyS0NQ',
    appId: '1:66332621949:ios:40fcbc43fa4adb850b0514',
    messagingSenderId: '66332621949',
    projectId: 'mynotes-camel-flutter',
    storageBucket: 'mynotes-camel-flutter.appspot.com',
    iosBundleId: 'com.camel.mynotes.RunnerTests',
  );
}
